spring.application.name=spring-ecommerce
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.config.import=optional:file:.env[.properties]

security.jwt.token.secret-key=${SECURITY_JWT_TOKEN_SECRET_KEY}
security.jwt.token.expire-length=${SECURITY_JWT_TOKEN_EXPIRE_LENGTH}