spring.application.name=spring-ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=name
spring.datasource.password=password
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.data-locations=classpath:data.sql
spring.datasource.url=jdbc:h2:mem:database
spring.datasource.initialization-mode=always
jwt.secret-key=NpE01joXvJ+AmqBYY72gwhBnEEKFod+zsqWEWck/tq4=
jwt.expire-length=3600000
#logging.level.root=DEBUG
