package ecommerce.controller

import io.restassured.RestAssured
import io.restassured.http.ContentType
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.http.HttpStatus
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.test.annotation.DirtiesContext

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
class ProductRestControllerTest {

    @Autowired
    lateinit var jdbcTemplate: JdbcTemplate

    private var productId: Long = -1

    @BeforeEach
    fun setUp() {
        jdbcTemplate.execute(
            """
            CREATE TABLE IF NOT EXISTS products (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                price DOUBLE NOT NULL,
                image_url VARCHAR(500)
            )
            """.trimIndent()
        )

        val productJson = """
            {
                "name": "cafe",
                "price": 39.0,
                "imageUrl": "https://test.com/image.jpg"
            }
        """.trimIndent()

        val response = RestAssured
            .given().log().all()
            .contentType(ContentType.JSON)
            .body(productJson)
            .`when`().post("/api/products")
            .then().extract().response()

        productId = response.jsonPath().getLong("id")
    }

    @Test
    fun addProduct() {
        val productJson = """
            {
                "name": "table",
                "price": 45.0,
                "imageUrl": "https://test.com/image2.jpg"
            }
        """.trimIndent()

        val response = RestAssured
            .given().log().all()
            .contentType(ContentType.JSON)
            .body(productJson)
            .`when`().post("/api/products")
            .then().extract().response()

        assertThat(response.statusCode).isEqualTo(HttpStatus.OK.value())
        val created = response.jsonPath()
        assertThat(created.getString("name")).isEqualTo("table")
        assertThat(created.getDouble("price")).isEqualTo(45.0)
        assertThat(created.getString("imageUrl")).isEqualTo("https://test.com/image2.jpg")
    }

    @Test
    fun getProducts_returnsList() {
        val response = RestAssured
            .given().log().all()
            .`when`().get("/api/products")
            .then().extract().response()

        assertThat(response.statusCode).isEqualTo(HttpStatus.OK.value())
        val productList = response.jsonPath().getList("", Map::class.java)
        assertThat(productList).isNotEmpty
    }
}
