DELETE FROM cart;
DELETE FROM members;
DELETE FROM products;

ALTER TABLE cart ALTER COLUMN id RESTART WITH 1;
ALTER TABLE members ALTER COLUMN id RESTART WITH 1;
ALTER TABLE products ALTER COLUMN id RESTART WITH 1;
