package ecommerce

import ecommerce.product.domain.Product
import ecommerce.product.repository.ProductRepository
import jakarta.validation.ValidationException
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.assertThrows
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest
import org.springframework.jdbc.core.JdbcTemplate

@JdbcTest
class ProductRepositoryTest {
    private lateinit var productRepository: ProductRepository

    @Autowired
    private lateinit var jdbcTemplate: JdbcTemplate

    @BeforeEach
    fun setUp() {
        productRepository = ProductRepository(jdbcTemplate)

        jdbcTemplate.execute("DROP TABLE products IF EXISTS")
        jdbcTemplate.execute(
            """
            CREATE TABLE products (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                price DECIMAL(10,2) NOT NULL,
                image_url VARCHAR(255) NOT NULL
            )
            """,
        )

        val products =
            listOf(
                Product(
                    id = null,
                    name = "Coca-Cola",
                    price = 2.00,
                    imageUrl = "https://mcdonalds.com.mt/wp-content/uploads/2024/06/COCA-COLA-WEBSITE-IMG.jpg",
                ),
                Product(
                    id = null,
                    name = "Fanta",
                    price = 2.50,
                    imageUrl =
                        "https://www.cokesolutions.com/content/dam/cokesolutions/us/images/Products" +
                                "/Fanta-Orange-PET.jpg",
                ),
                Product(
                    id = null,
                    name = "Cappuccino",
                    price = 4.39,
                    imageUrl =
                        "https://www.tchibo.de/kaffeeakademie/media/pages/global-images/fb95bb5370-1729609446/" +
                                "adobestock_219364830-1440x700-crop-42-46.jpg",
                ),
            )

        jdbcTemplate.batchUpdate(
            "INSERT INTO products(name, price, image_url) VALUES (?, ?, ?)",
            products,
            products.size,
        ) { ps, product ->
            ps.setString(1, product.name)
            ps.setDouble(2, product.price)
            ps.setString(3, product.imageUrl)
        }
    }

    @Test
    fun `find all products`() {
        val products = productRepository.findAllProducts()
        assertThat(products).hasSize(3)

        val expectedProducts =
            listOf(
                Product(
                    id = 1,
                    name = "Coca-Cola",
                    price = 2.00,
                    imageUrl = "https://mcdonalds.com.mt/wp-content/uploads/2024/06/COCA-COLA-WEBSITE-IMG.jpg",
                ),
                Product(
                    id = 2,
                    name = "Fanta",
                    price = 2.50,
                    imageUrl =
                        "https://www.cokesolutions.com/content/dam/cokesolutions/us/images/Products" +
                                "/Fanta-Orange-PET.jpg",
                ),
                Product(
                    id = 3,
                    name = "Cappuccino",
                    price = 4.39,
                    imageUrl =
                        "https://www.tchibo.de/kaffeeakademie/media/pages/global-images/fb95bb5370-1729609446/" +
                                "adobestock_219364830-1440x700-crop-42-46.jpg",
                ),
            )
        assertThat(products).isEqualTo(expectedProducts)
    }

    @Test
    fun `insert new product`() {
        val product =
            Product(
                name = "Sprite",
                price = 1.99,
                imageUrl = "https://example.com/sprite.jpg",
            )
        productRepository.insert(product)

        val products = productRepository.findAllProducts()
        assertThat(products).hasSize(4)
        assertThat(
            products.any {
                it.name == "Sprite" && it.price == 1.99 && it.imageUrl == "https://example.com/" +
                    "sprite.jpg"
            },
        ).isTrue()
        assertThat(product.id).isNotNull()
    }



    @Test
    fun `edit existing product`() {
        val product =
            Product(
                name = "Sprite",
                price = 1.99,
                imageUrl = "https://example.com/sprite.jpg",
            )
        productRepository.edit(product, 1)

        val products = productRepository.findAllProducts()
        assertThat(products).hasSize(3)
        assertThat(products.first().name).isEqualTo("Sprite")
        assertThat(products.first().price).isEqualTo(1.99)
        assertThat(products.first().imageUrl).isEqualTo("https://example.com/sprite.jpg")
        assertThat(products.any { it.name == "Coca-Cola" }).isFalse()
    }


    @Test
    fun `delete product`() {
        productRepository.delete(1)

        val products = productRepository.findAllProducts()
        assertThat(products).hasSize(2)
        assertThat(products.any { it.name == "Coca-Cola" }).isFalse()
    }

    @Test
    fun `insert product with non-unique name should throw ValidationException`() {
        val product = Product(
            name = "Coca-Cola",
            price = 3.00,
            imageUrl = "https://example.com/cola.jpg"
        )
        assertThrows<ValidationException> {
            productRepository.insert(product)
        }.also { exception ->
            assertThat(exception.message).isEqualTo("Product name must be unique")
        }
    }

    @Test
    fun `edit product with non-unique name should throw ValidationException`() {
        val product = Product(
            name = "Fanta",
            price = 3.00,
            imageUrl = "https://example.com/fanta.jpg"
        )
        assertThrows<ValidationException> {
            productRepository.edit(product, 1)
        }.also { exception ->
            assertThat(exception.message).isEqualTo("Product name must be unique")
        }
    }

}
